server:
  port: 9000

spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: CRUD-SERVICE
          uri: lb://CRUD-SERVICE
          predicates:
            - Path=/crud/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
